version: '3'
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule: "Host(`portainer-mq.th.denarm.be`)"
      - "traefik.http.routers.portainer.entrypoints: "web"
      - "traefik.http.routers.portainer.middlewares: "ssl@file"
      - "traefik.http.routers.portainer-ssl.rule: "Host(`portainer-mq.th.denarm.be`)"
      - "traefik.http.routers.portainer-ssl.entrypoints: "websecure"
      - "traefik.http.routers.portainer-ssl.tls: "true"
      - "traefik.http.routers.portainer-ssl.tls.certresolver: "letsencrypt"
    volumes:
    - /opt/threathunt/portainer/data:/data
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
    networks:
      - elastic

networks:
  elastic:
    driver: bridge